// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9yVkdGNTeu6yUEuxkmNVioiL3lsKCmWg',
    appId: '1:851261172791:web:c8503f250bb04be6fb63b2',
    messagingSenderId: '851261172791',
    projectId: 'gold-circle-83b88',
    authDomain: 'gold-circle-83b88.firebaseapp.com',
    storageBucket: 'gold-circle-83b88.firebasestorage.app',
    measurementId: 'G-S8CXY8LWFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1EIEZVdE2V0FyIXB6LWeRvN_guPRD-iI',
    appId: '1:851261172791:android:539e9a238520b11efb63b2',
    messagingSenderId: '851261172791',
    projectId: 'gold-circle-83b88',
    storageBucket: 'gold-circle-83b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_F_KmYXPgPo8XoTrffQBF2sRrfJzQhLk',
    appId: '1:851261172791:ios:522a204edc4dc85cfb63b2',
    messagingSenderId: '851261172791',
    projectId: 'gold-circle-83b88',
    storageBucket: 'gold-circle-83b88.firebasestorage.app',
    iosBundleId: 'com.blacksun.goldcircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_F_KmYXPgPo8XoTrffQBF2sRrfJzQhLk',
    appId: '1:851261172791:ios:522a204edc4dc85cfb63b2',
    messagingSenderId: '851261172791',
    projectId: 'gold-circle-83b88',
    storageBucket: 'gold-circle-83b88.firebasestorage.app',
    iosBundleId: 'com.blacksun.goldcircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9yVkdGNTeu6yUEuxkmNVioiL3lsKCmWg',
    appId: '1:851261172791:web:71375946fd3c8d4dfb63b2',
    messagingSenderId: '851261172791',
    projectId: 'gold-circle-83b88',
    authDomain: 'gold-circle-83b88.firebaseapp.com',
    storageBucket: 'gold-circle-83b88.firebasestorage.app',
    measurementId: 'G-7JVQW1BSHR',
  );
}
